"""initial

Revision ID: 7090f1d9a6ae
Revises: 
Create Date: 2026-08-02 07:53:06.294537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7090f1d9a6ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('source', sa.Enum('LEADER', 'JUNIOR', name='activitysource'), nullable=False),
    sa.Column('default_premiles', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pgms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('SUPERVISOR', 'LIDER', 'JUNIOR', name='userrole'), nullable=False),
    sa.Column('pgm_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pgm_id'], ['pgms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('checklist_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('junior_id', sa.Integer(), nullable=False),
    sa.Column('activity_type_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('premiles_awarded', sa.Integer(), nullable=False),
    sa.Column('credited_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], ),
    sa.ForeignKeyConstraint(['credited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['junior_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('junior_id', 'activity_type_id', 'activity_date', name='uq_checklist_daily')
    )
    op.create_table('manual_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('junior_id', sa.Integer(), nullable=False),
    sa.Column('activity_type_id', sa.Integer(), nullable=False),
    sa.Column('premiles_awarded', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('launched_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], ),
    sa.ForeignKeyConstraint(['junior_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['launched_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pgm_leaders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pgm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pgm_id'], ['pgms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pgm_id', name='uq_pgm_leader')
    )
    op.create_table('premiles_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('junior_id', sa.Integer(), nullable=False),
    sa.Column('total_balance', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['junior_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('junior_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('premiles_balance')
    op.drop_table('pgm_leaders')
    op.drop_table('manual_logs')
    op.drop_table('checklist_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('pgms')
    op.drop_table('activity_types')
    # ### end Alembic commands ###
